티켓 예매 다양한 락 기법 적용 / 테스트 데이터 클리너 적용
f-lab-edu/ticketpark pull request #10
Opened 2024-08-19 13:21 UTC by skdev0619

#  티켓 예매 다양한 락 기법 적용

## 변경 사항
- 테스트 실행 후 테스트 데이터 제거를 위한 TestDataCleaner 생성 
- 티켓 예매에 비관적, 낙관적, 네임드 락 적용하여 동시성 이슈 해결
- 다양한 락 전략 제공 위해서 인터페이스를 통한 DI 적용
  - 다이어그램 참고
 ![도식도-예매 구현체 drawio](https://github.com/user-attachments/assets/2f892463-4980-40da-81ee-6e286856452d)

## 예매 도식도
예매는 아래 3단계로 실행된다.
1) 선택한 좌석 등급의 좌석 수를 조회하여 좌석 수가 1이상인지 확인
2) 선택한 좌석 등급, 좌석 정보(ex1층 A열1번 자리)가 예매됐는지 확인
3) 선택한 좌석 등급의 좌석 수의 티켓 1장 감소, 예매정보 저장

![도식도-예매 전체 도식도 drawio](https://github.com/user-attachments/assets/7be37e42-cf67-4916-9f12-0fef8765f04c)
 
## 비관적 락
- 선택한 좌석 등급의 좌석 수 조회 쿼리에 락 적용(ticket_grade 테이블의 1 row)
- 선택한 좌석 등급, 좌석 정보 조회 쿼리에 락 적용(ticket_order 테이블의 1 row)
- ticket_grade, ticket_order 테이블 각각 1 row에 락을 걸고 티켓 등급 update, 예매 정보 insert하도록 구현

## 낙관적 락
- 선택한 좌석 등급의 티켓 매수 감소 시 낙관적 락 적용
- 선택한 좌석 등급의 버전 정보를 조회 후, 조회한 버전 정보로 조건을 걸어서 티켓 장수를 감소시킨다
- update된 row가 없다면 낙관적 락 exception 발생시켜서 티켓 예매 재처리 시도한다.
  - 재처리의 경우 AOP로 구현
  - 낙관적 락 실패 시 재처리 횟수는 application.yml에서 설정하도록 변경
```
retry:
  optimisticLock:
    count : 5
``` 
- 예매 가능한 좌석 수 체크하는 로직이 두 번 들어감
**1. 예매 가능 좌석 수 체크**
   2. 해당 좌석 예매 됐는지 확인
**3. 예매 가능 좌석 수 체크**
        해당 좌석 등급의 티켓 수 감소
        예매 정보 저장
  
- 이유 
`낙관적 락 멀티스레드 환경`에서 실행 시, `낙관적 락 실패 시 실행되는 예매 retry`로 인해서
첫번째 예매 좌석 수 체크에서는 남아있는 좌석이 존재하지만
세번째 예매 가능 좌석 수 체크에서는 좌석이 존재하지 않는 경우가 있어서
두 번의 좌석 수 체크 로직이 들어갔습니다.

- 낙관적 락 도식도
![도식도-낙관적 락 drawio (1)](https://github.com/user-attachments/assets/efa6506a-dd8c-4488-973f-447c2995542f)

## 네임드락
maria db의 네임드 락 이용
락 획득 - 예매 로직 실행 - 락 해제로 실행됩니다
1. 락 획득
2. 예매 가능 좌석 수 체크
3. 해당 좌석 예매 됐는지 확인
4. 해당 좌석 등급의 티켓 수 감소
   예매 정보 저장
5. 락 해제

2024-08-20 22:21 UTC, f-lab-inno requested changes

2024-08-20 22:21 UTC, f-lab-inno commented on src/main/java/com/ticketpark/ticket/service/TicketGradeServiceByNamedLock.java
> +    public boolean isFullBooked(TicketOrderDto dto){
Named Lock이 어떻게 적용되는걸까요? 쿼리나 AOP 적용부분이 안보이는듯해서요~!

2024-08-20 22:21 UTC, f-lab-inno commented on src/main/java/com/ticketpark/ticket/service/TicketGradeService.java
> +public interface TicketGradeService {
Facade 레벨에서 Lock 전략이 정해지는것 이외에도 서비스 레벨에서도 Lock 전략이 나뉠필요가 있는걸까요? 개인적인 의견으로는 LockTemplate을 만들고 해당 LockTemplate 내에서 어떠한 쿼리에 대해 어떤 락을 사용할지 결정할수 있도록 API를 설계하여 사용하는게 조금 더 유연하지 않을까 싶습니다.

지금 구조에서는 매번 락이 필요할때마다 이런 서비스 다형성 구현이 되어야할것 같아요

2024-08-20 22:21 UTC, f-lab-inno commented on src/main/java/com/ticketpark/ticket/service/OptimisticLockRetryAspect.java
> +    private byte retryCount;
이렇게 aspect class의 인스턴스 변수를 활용해도 문제가 없나요?

해당 클래스는 싱글톤이고, Spring AOP 기반 런타임 위빙이 되기 때문에 공유될것 같은데요!

2024-08-20 22:21 UTC, f-lab-inno commented on src/test/java/com/ticketpark/common/TestDataCleaner.java
> +
해당 데이터베이스 스키마의 모든 테이블 정보를 읽어와서 delete를 해주는것도 나쁘지 않을것 같아요! (매번 Repository가 추가됐을때를 고려)

2024-08-20 22:21 UTC, f-lab-inno commented on src/test/java/com/ticketpark/ticket/service/TicketOrderMultiThreadTest.java
> +                    boolean isActiveTran = TransactionSynchronizationManager.isActualTransactionActive();
사용되지 않는것 같아요

2024-08-20 22:21 UTC, f-lab-inno commented on src/test/java/com/ticketpark/ticket/service/TicketOrderMultiThreadTest.java
> +
Test LifeCycle Hook Method는 관례적으로 가장 상위에 정의하는게 일반적입니다!

2024-08-29 07:39 UTC, skdev0619 commented on src/main/java/com/ticketpark/ticket/service/TicketGradeServiceByNamedLock.java
> +    public boolean isFullBooked(TicketOrderDto dto){
TicketOrderFacadeByNamedLock에서 락 get > 로직 실행 > 락 해제 형태로 실행되고 있습니다

2024-08-29 07:39 UTC, skdev0619 commented on src/main/java/com/ticketpark/ticket/service/TicketGradeService.java
> +public interface TicketGradeService {
넵 고민해보겠습니다!!

2024-08-29 07:40 UTC, skdev0619 commented on src/main/java/com/ticketpark/ticket/service/OptimisticLockRetryAspect.java
> +    private byte retryCount;
보니까 절대로 공유되면 안되는 변수네요!!
retryCount 지역변수로 값 할당해서 수정하도록 하겠습니다.

2024-08-29 07:40 UTC, skdev0619 commented on src/test/java/com/ticketpark/common/TestDataCleaner.java
> +
넵 수정하겠습니다

2024-08-29 07:41 UTC, skdev0619 commented on src/test/java/com/ticketpark/ticket/service/TicketOrderMultiThreadTest.java
> +
넵 반영하겠습니다

2024-08-29 07:41 UTC, skdev0619 commented on src/test/java/com/ticketpark/ticket/service/TicketOrderMultiThreadTest.java
> +                    boolean isActiveTran = TransactionSynchronizationManager.isActualTransactionActive();
넵 반영하겠습니다

2024-08-29 23:52 UTC, merged