[#2] 회원가입 보완 및 테스트케이스 작성
f-lab-edu/ticketpark pull request #2
Opened 2024-07-10 08:06 UTC by skdev0619

- 코드 리뷰 반영
  - custom httpStatus 생성(TicketParkHttpStatus.java) 
- mybatis 적용
- 회원가입 테스트 코드 추가

2024-07-14 03:56 UTC, f-lab-inno requested changes

2024-07-14 03:56 UTC, f-lab-inno commented on src/main/java/com/ticketpark/ticket/configuration/RepositoryConfig.java
> +    }
다형성 활용으로 필요시 DB 구현체를 갈아끼울수 있겠네요 👍

2024-07-14 03:56 UTC, f-lab-inno commented on src/main/java/com/ticketpark/ticket/exception/TicketParkHttpStatus.java
> +    private final int httpCode;
HTTP code가 비즈니스 에러에 필요할까요?

2024-07-14 03:56 UTC, f-lab-inno commented on src/main/java/com/ticketpark/ticket/member/controller/request/MemberJoinRequest.java
> +    private Timestamp updated_dt;
Timestamp 보다는 LocalDateTime을 이용해주세요!

비교적 모던한 시간단위의 객체인 JSR-310 스펙에 대해 알아보세요
- https://jcp.org/aboutJava/communityprocess/pfd/jsr310/JSR-310-guide.html
https://sejoung.github.io/2018/06/2018-06-21-JSR310/

2024-07-14 03:56 UTC, f-lab-inno commented on src/main/java/com/ticketpark/ticket/member/controller/request/MemberJoinRequest.java
> +    private Timestamp updated_dt;
참고로 Timestamp는 sql 패키지 하위에 있는 DB 타입과 상호작용하기 위한 클래스입니다.

2024-07-14 03:56 UTC, f-lab-inno commented on src/main/java/com/ticketpark/ticket/member/model/entity/MemberStatus.java
> +    }
요런것들은 어떻게 테스트할 수 있을지 고민해보실까요?

2024-07-14 03:56 UTC, f-lab-inno commented on src/main/java/com/ticketpark/ticket/member/model/dto/MemberDto.java
>      private MemberStatus use_yn;
이것도 어떻게 테스트할 수 있을지 고민해보실까요?

2024-07-15 06:00 UTC, skdev0619 commented on src/main/java/com/ticketpark/ticket/exception/TicketParkHttpStatus.java
> +    private final int httpCode;
ControllerAdvice에서 status 값 출력 위해서 추가했습니다.
비즈니스 에러에서 status_code 값이 response 출력 외에 쓰이는 용도가 없어서
제거해도 무관합니다.
![image](https://github.com/user-attachments/assets/d2eb75df-43d7-406d-84d1-3b10211707f1)

2024-07-15 07:01 UTC, skdev0619 commented on src/main/java/com/ticketpark/ticket/member/model/entity/MemberStatus.java
> +    }
저라면 리턴 값이 enum의 value 아님 null이어서
null인 경우인 BadRequestException 리턴하는 방향으로 테스트케이스 구현할거 같습니다.

2024-07-15 07:11 UTC, skdev0619 commented on src/main/java/com/ticketpark/ticket/member/model/dto/MemberDto.java
>      private MemberStatus use_yn;
1. @NotBlank를 예로 들자면
어노테이션 적용한 값과 ""과 비교하는 방식

2. Spring Bean Validation API 사용해서 검증하는 방식
ex) Validation.buildDefaultValidatorFactory().getValidator()
두 가지 방법 중 택일하여 구현할 거 같습니다.

2024-07-17 04:45 UTC, merged