공연/티켓 추가 및 테스트케이스 작성
f-lab-edu/ticketpark pull request #4
Opened 2024-07-18 08:15 UTC by skdev0619

### 공연/티켓 등록 api 추가
#### 공연/티켓 등록 관련 상세
- 공연 등록 시, 티켓 정보(티켓 정보, 좌석등급)도 함께 등록한다
	- 공연, 티켓 각각 단독으로 등록은 불가하다
#### 테스트 시나리오
- 공연
   - 공연, 가수, 티켓정보, 좌석정보 request 유효하면 정상 동작한다
   - 티켓 request 없이 공연 등록 불가하다

- 티켓
   - 티켓 단독으로 등록 불가하다.  무조건 공연과 함께 등록되어야 한다.
     티켓 단독 등록 트랜잭션 전파 관련 Exception(IllegalTransactionStateException) 리턴

### 공연/티켓 추가 도식도
![공연api](https://github.com/user-attachments/assets/4b6b231c-878f-4874-83b9-0aff1808c8e6)

2024-07-20 14:18 UTC, f-lab-inno requested changes

2024-07-20 14:18 UTC, f-lab-inno commented on src/main/java/com/ticketpark/performance/model/dto/PerformanceDto.java
> -@AllArgsConstructor
가능하면 필수적인 필드의 생성자, getter, setter에 대해서만 열어주세요!

2024-07-20 14:18 UTC, f-lab-inno commented on src/main/java/com/ticketpark/performance/model/entity/Performance.java
>          performance.setCreated_at(LocalDateTime.now());
request에서 이 일을 담당하는것이 더 기능 응집에 좋지 않을까요?

2024-07-20 14:18 UTC, f-lab-inno commented on src/main/java/com/ticketpark/performance/repository/PerformerMapper.java
> +    void createPerformer(List<Performer> performerList);
List라는 명칭보다는 가능하면 복수형 `performers` 등을 사용해주세요! (List라는것은 이미 자료형으로 표현이 가능하기 때문)

- https://tecoble.techcourse.co.kr/post/2020-04-24-variable_naming/

2024-07-20 14:18 UTC, f-lab-inno commented on src/main/java/com/ticketpark/performance/service/PerformanceService.java
> +            );
Optional은 클라이언트에서 null 가능성을 인지하고 다음 핸들링을 유도하도록 하는 클래스이기 때문에, 이미 이곳에서는 null 가능성이 인지되는 상황으로 보여서 그냥 if문 처리나 `Objects.requireNonNull`, `java assert`  별도의 null 체크 로직을 표현해주시는것이 좋을것 같아요!

- https://www.baeldung.com/java-assert
- https://careerly.co.kr/comments/87740

2024-07-20 14:18 UTC, f-lab-inno commented on src/main/java/com/ticketpark/performance/controller/PerformanceController.java
> +    @PostMapping("/createPerformance")
이미 Post HTTP Method로 리소스 행위에 대해서 표현이 가능하기 때문에 create라는 명칭은 꼭 필요하지 않다면 생략해도 될것 같아요

2024-07-20 14:18 UTC, f-lab-inno commented on src/main/java/com/ticketpark/performance/model/entity/Performer.java
> +    public static List<Performer> getPerformerList(Long performanceId, PerformanceCreateRequest request){
더 외부의 객체인 PerformanceCreateRequest를 내부 객체인 Performer에서 의존하는 경우 어떠한 부작용이 있을까요?

2024-07-20 14:18 UTC, f-lab-inno commented on src/main/java/com/ticketpark/ticket/model/entity/Ticket_grade.java
>  public class Ticket_grade {
가능하면 Java Class명은 CamelCase를 사용해주세요!

2024-07-20 14:18 UTC, f-lab-inno commented on src/test/java/com/ticketpark/member/controller/MemberControllerTest.java
> +        request = MemberFixture.getJoinRequest();
👍

2024-07-20 14:18 UTC, f-lab-inno commented on src/test/java/com/ticketpark/performance/controller/PerformanceControllerTest.java
> +
이러한 테스트가 앞으로도 반복될것 같은데 상위 클래스로 추상화해도 좋겠네요~

2024-07-20 14:18 UTC, f-lab-inno commented on src/test/java/com/ticketpark/performance/fixture/PerformanceFixture.java
> +        LocalDateTime performanceEndTime = LocalDateTime.now().plusDays(12);
가능하면 테스트에는 고정시간을 사용해주세요! 좋은 테스트를 위한 FIRST 속성을 기억해주세요!

2024-07-23 01:44 UTC, merged

2024-07-23 08:20 UTC, skdev0619 commented on src/main/java/com/ticketpark/performance/model/entity/Performer.java
> +    public static List<Performer> getPerformerList(Long performanceId, PerformanceCreateRequest request){
순환참조 가능성이 있어보입니다

2024-07-23 08:27 UTC, skdev0619 commented on src/main/java/com/ticketpark/performance/model/entity/Performance.java
>          performance.setCreated_at(LocalDateTime.now());
네 말씀해주신거 처럼 request 파싱해서 새로운 객체로 만드는 내용들은 request로 다 옮기는게 나아 보입니다.